services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=airflowfernetkey
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflowsecretkey
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        airflow db upgrade && \
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    volumes:
      - ./data-pipeline/dags:/opt/airflow/dags
      - ./data-pipeline/data:/opt/airflow/data
    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=airflowfernetkey
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflowsecretkey
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./data-pipeline/dags:/opt/airflow/dags
      - ./data-pipeline/data:/opt/airflow/data
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=airflowfernetkey
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflowsecretkey
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
    command: scheduler
    volumes:
      - ./data-pipeline/dags:/opt/airflow/dags
      - ./data-pipeline/data:/opt/airflow/data
    restart: always
